#!/bin/sh
set -eu

if [ $# = 0 ]; then
    echo "Usage: nx ENVIRONMENT-NAME [COMMAND...]"
    echo ""
    echo "Other Commands:"
    echo "nx -list    list all environments"
    echo "nx -add ?   should I add this?"
    exit 1
fi

script_dir=$(dirname "$(readlink -f -- "$0")")
first=$1
shift

if [ "$first" == "-list" ]; then
    for env in $(find $script_dir/env -maxdepth 1 -type f); do
	echo "$(basename $env): $(cat $env)"
    done
    exit 0
fi

env=$script_dir/env/$first
if [ ! -e "$env" ]; then
    echo "Error: nx environment '$first' does not exist"
    exit 1
fi

pkgs=$(cat $env)

# we use a nix-expression rather than -p packages... so we can remove standard packages for
# a more pure environment
mkshell='with import <nixpkgs> { };'\
'runCommandNoCC "name" {'\
'  buildInputs = [ '$pkgs' ];'\
'} ""'

if [ $# = 0 ]; then
    echo nix-shell --pure --expr "'$mkshell'"
    exec nix-shell --pure --expr "$mkshell"
fi

exec nix-shell --pure --expr "$mkshell" --run "$*"
